flake/nixpkgs: 25.11 → 26.05
Running `cargo semver-checks` errors with

    error: unsupported rustdoc format v57 for file:
    …/heartwood/target/semver-checks/local-radicle-…/target/doc/radicle.json
    (supported formats are v53, v55, v56)

Support for rustdoc format v57 is part of cargo-semver-checks 0.46,
which is not part of NixOS 25.11, which has reached EOL.

Re-point the "nixpkgs-stable" input to NixOS 26.05 to reach a newer
cargo-semver-checks and a NixOS version that is supported.

Update the flake.